version: '3.8'
services:
  myhome-dev:
    image: myhome
    networks:
      - dev
#    depends_on:
#      - db
    ports:
      - "8120:8120"
#  postgres:
#    image: postgres:latest
#    env_file:
#      - db.env
#    volumes:
#      - /db:/var/lib/postgresql/data
#    networks:
#      - dev
#    ports:
#      - "5432:5432"
volumes:
  db:
networks:
  dev: