version: "3.9"
services:
  user:
    image: user:1.0
    ports:
      - 8080:8080
    networks:
      - user
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./db.env
    volumes:
      - pg-volume:/var/lib/postgresql/data/
      - ./init.script.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - user
      - admin
  admin:
    image: admin:1.0
    ports:
      - 8085:8085
    networks:
      - admin
volumes:
  pg-volume:
networks:
  user:
  admin: